### ISSUE TITLE
argument to specify dataset_train/dataset_eval

### ISSUE THREAD

**Issue by rambleramble** [burchim/AVEC#1]
Thanks for the great work, it seems the main uses dataset_train/dataset_eval as variables but not in its argument. Could you help to check on how to pass the dataset_train/dataset_eval?  Thanks!

**Comment by burchim** [comment]
Hi,

The dataset_train and dataset_eval are automatically loaded by the main using the [load_dataset](https://github.com/burchim/AVEC/blob/535f534607064f2ecc59947ff0b2350d1eda80c3/main.py#L55) function. They need to be instantiated in the config files using the [dataset_train](https://github.com/burchim/AVEC/blob/535f534607064f2ecc59947ff0b2350d1eda80c3/configs/LRS23/AV/EffConfInterCTC.py#L90) and [evaluation_dataset](https://github.com/burchim/AVEC/blob/535f534607064f2ecc59947ff0b2350d1eda80c3/configs/LRS23/AV/EffConfInterCTC.py#L114) variables. All these config variables including model and other hyper-parameters are then gathered for training/evaluation using args.

If you want to change datasets or use other datasets, you can simply edit the config file.

Best,
Maxime

**Comment by ningzhang-paiigit** [comment]
Thank you very much!, it wokred.

**Comment by rambleramble** [comment]
It works thanks a lot!
