### ISSUE TITLE
Transcription output

### ISSUE THREAD

**Issue by chaufanglin** [burchim/AVEC#10]
Hi,

Good paper! I'm trying to run your trained model and want to get some transcriptions. However, I find it difficult to save the transcriptions to a file so that I can do some research. Could you please help me with that?

Many thanks,
Zhaofeng

**Comment by burchim** [comment]
Hi, 

Thanks for your interest in the paper.

Are you trying to transcribe a list of audio files?

This should be easy to do by adding a "transcribe" function to "AudioEfficientConformerInterCTC", "VisualEfficientConformerInterCTC" and "AudioVisualEfficientConformerInterCTC" in models_zoo.py similar to what is done in the NeMo toolkit.
The function could take the list of audio file paths as argument, return a list of transcriptions. 
You could then use this function to transcribe your data and then save them to a text file.

**Comment by chaufanglin** [comment]
Hi,
Thanks a lot for your suggestion. I will try that! 
Many thanks
