### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by jeonhuhuhu** [burchim/AVEC#12]
"I would appreciate it if you could kindly provide the necessary details and data associated with code **download_checkpoints_and_tokenizers.py** again. 

I'm currently facing an issue preventing me from downloading the related information, and I need it to run the code successfully. 

Thank you for your assistance."

**Comment by jeonhuhuhu** [comment]
> "I would appreciate it if you could kindly provide the necessary details and data associated with code **download_checkpoints_and_tokenizers.py** again.
> 
> I'm currently facing an issue preventing me from downloading the related information, and I need it to run the code successfully.
> 
> Thank you for your assistance."

We manually downloaded and processed the data one by one.

**Comment by burchim** [comment]
Hi, what was the error or issue that you encountered ?

The demo notebook provide a demo on how to download checkpoints and evaluate the models: https://colab.research.google.com/github/burchim/AVEC/blob/master/demo.ipynb

Best,
Maxime

**Comment by jeonhuhuhu** [comment]
> Hi, what was the error or issue that you encountered ?
> 
> The demo notebook provide a demo on how to download checkpoints and evaluate the models: https://colab.research.google.com/github/burchim/AVEC/blob/master/demo.ipynb
> 
> Best, Maxime

There was an issue with your Google Drive connection preventing outsiders from accessing it, but it has been resolved. For the second problem, can you share a detailed version of **CUDA, Pytorch, torchaudio, torchvision**?

**Comment by burchim** [comment]
Yes Google Drive can sometimes returns an error saying that the file was downloaded too many times in a short period.

Concerning the version of libraries, I was using PyTorch 1.12 with torchaudio 0.12 and torchvision 0.13.

I was also using cuda 11.2 for A100 GPU support.

**Comment by jeonhuhuhu** [comment]
> Yes Google Drive can sometimes returns an error saying that the file was downloaded too many times in a short period.
> 
> Concerning the version of libraries, I was using PyTorch 1.12 with torchaudio 0.12 and torchvision 0.13.
> 
> I was also using cuda 11.2 for A100 GPU support.


Your installation process is perfectly well explained. However, if we repeatedly install ctcdecode, the following error keeps occurring and I cannot install it. Can you share the installation method?

 **subprocess.CalledProcessError: Command '['which', 'x86_64-conda_cos7-linux-gnu-c++']' returned non-zero exit status 1.
      [end of output]**
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ctcdecode
  Running setup.py clean for ctcdecode
Failed to build ctcdecode
ERROR: Could not build wheels for ctcdecode, which is required to install pyproject.toml-based projects

**Comment by jeonhuhuhu** [comment]
> > Yes Google Drive can sometimes returns an error saying that the file was downloaded too many times in a short period.
> > Concerning the version of libraries, I was using PyTorch 1.12 with torchaudio 0.12 and torchvision 0.13.
> > I was also using cuda 11.2 for A100 GPU support.
> 
> Your installation process is perfectly well explained. However, if we repeatedly install ctcdecode, the following error keeps occurring and I cannot install it. Can you share the installation method?
> 
> **subprocess.CalledProcessError: Command '['which', 'x86_64-conda_cos7-linux-gnu-c++']' returned non-zero exit status 1. [end of output]**
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for ctcdecode Running setup.py clean for ctcdecode Failed to build ctcdecode ERROR: Could not build wheels for ctcdecode, which is required to install pyproject.toml-based projects

"I have managed to succeed in the installation and have shared the installation method."
https://github.com/parlance/ctcdecode/issues/229

**Comment by burchim** [comment]
Hi, thanks for your return.

Yes CTCdecode can sometimes fail to install when using specific PyTorch versions.
I know it is working well with PyTorch 2.0.0 and under.

Hope you could successfully evaluate the models and/or do some experiments with the repo.
