### ISSUE TITLE
LRS2-Pretrain.txt

### ISSUE THREAD

**Issue by TryHard-LL** [burchim/AVEC#4]
Hello, thank for your excellent work.
Where  can I get the  "LRS2-Pretrain.txt" ?
The dataset I downloaded does not have the file.

**Comment by burchim** [comment]
Hi, 

If you are talking about the LRS2 pretrain.txt file that contains samples ids, you can download it [here](https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html).

All the necessary files can automatically be downloaded using the download_and_prepare_datasets.py [script](https://github.com/burchim/AVEC/blob/master/download_and_prepare_datasets.py). This script will download and prepare the LRW/LRS2/LRS3 datasets, you will just need to add your datasets username and password [here](https://github.com/burchim/AVEC/blob/1bf8ad079b90af383090f1584a20fe9467f98f47/download_and_prepare_datasets.py#L8). It will also generate corpus files for all dataset splits to train languages models / ngrams.

**Comment by HBU-Lin-Li** [comment]
Thank for your reply,
but I get this error 
![image](https://user-images.githubusercontent.com/56581796/223892184-f6d87617-e300-4bf6-8cf2-6dccbd11e3f1.png)

I don not have a account~
Could you share me in the Google Drive or others?
Thank you~

**Comment by TryHard-LL** [comment]
Thank you~

**Comment by burchim** [comment]
You welcome, to get access to the datasets (username and password) you will need to fill the [BCC forms](https://www.bbc.co.uk/rd/projects/lip-reading-datasets) and send it to rob.cooper [at] bbc.co.uk.

**Comment by Eric-is-good** [comment]
> Hello, thank for your excellent work. Where can I get the "LRS2-Pretrain.txt" ? The dataset I downloaded does not have the file.

do you have pretrain.txt? can you give me a copy?

**Comment by burchim** [comment]
@Eric-is-good  Hi, to get access to LRS2 ressources, you will need to fill a [form](https://www.bbc.co.uk/rd/projects/lip-reading-datasets) and send it to rob.cooper [at] bbc.co.uk. You should then receive a personal password + username to download the LRS2 pretrain.txt [here](https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html). The dataset ressources cannot be shared to the public unfortunately. Only people who have received their personal identification can access it.
