### ISSUE TITLE
i faced few issues while launching your code

### ISSUE THREAD

**Issue by natapuskareva** [burchim/AVEC#5]
hello! i've got these problems with AVEC project (i used Google Notebook to work):
i don't understand clearly what should i do with dataset. is it built-in into code or should i make it myself?
also in the part "load and test model on samples" the program doesn't understand "import nnet". it says "import nnet could not be resolved".
and it doesn't work at all when i delete file "macron.crop" :( it should create this file himself but it doesn't
could you help me, please?

**Comment by natapuskareva** [comment]
i think the main problem in torch (because sometimes it says "no module named ibug") and in nnet. and i don't know how i can deal with it

**Comment by burchim** [comment]
Hi,

The datasets used for this project are the LRW, LRS2 and LRS3 datasets. You will need to fill a [form](https://www.bbc.co.uk/rd/projects/lip-reading-datasets) to receive a username and password and access them. `python download_and_prepare_datasets.py` will download and prepare the datasets automatically. (just need to add your username and password [here](https://github.com/burchim/AVEC/blob/1bf8ad079b90af383090f1584a20fe9467f98f47/download_and_prepare_datasets.py#L8))

The issue you are facing may be due face_detection/face_alignment packages that require a notebook restart to be imported correctly. Maybe simply restarting the notebook will solve the issue. You will then be able to detect face landmarks to regenerate macron_crop.mp4.

**Comment by natapuskareva** [comment]
hi,
i've already tried to do that. but BBC has answered that i'm not an official account and hasn't given a permission to me. maybe the problem is that i'm from Russia. the restarting notebook to solve the next issue also hasn't worked, and i can send a photo to show how does my problem look

**Comment by burchim** [comment]
Unfortunately, I cannot really help you with that :(

Can you send the error you are having? I do not encounter any issue while running the demo notebook.

**Comment by natapuskareva** [comment]
(it's a beginning of part "load and test model on samples")
![image](https://user-images.githubusercontent.com/126642210/231346180-38914f9a-c04d-42c2-ae14-53d7f2d6c7a8.png)
it doesn't understand "nnet"
![image](https://user-images.githubusercontent.com/126642210/231346743-628f65dd-eb20-4b52-8e7d-bc5529c41dcb.png)
and after launching it says "no module named ibug"

![image](https://user-images.githubusercontent.com/126642210/231347737-567a66fb-7f62-4762-9585-2fbe88aae381.png)
and idk are these results okay or not ("model loaded on step 0")

![image](https://user-images.githubusercontent.com/126642210/231348298-f9b5d258-5d8f-4db7-9b96-ef6f45e0bcbe.png)
and deleting "macron.crop" causes one more mistake

i can't understand the reasons of all that mistakes, but i suppose not all of them are due to the dataset's absence

**Comment by natapuskareva** [comment]
maybe can i use your username and password to use the datasets?

**Comment by burchim** [comment]
Hi, the error happens because face_detection/face_alignment packages require a notebook restart after installation to be imported. Restarting the notebook (runtime->restart runtime) will fix the issue. Simply restart the notebook and run the import nnet cell again.

The "model loaded on step 0" happens because pretrained model checkpoints do not include the optimizer state dictionary that is not needed for evaluation, the checkpoints only include the pretrained weights to reduce its size.

Sorry, the datasets username/password are personal and cannot be shared. Only persons granted access by the BBC can receive a username/password to download the datasets.
