### ISSUE TITLE
pytorch-version

### ISSUE THREAD

**Issue by liyuandagege** [burchim/AVEC#6]
i can't find version of python、pytorch etc , them play a very important roel in train and test, can you give some imformation about this?

**Comment by burchim** [comment]
Hi,

I suppose that I used PyTorch 1.12 with Torchvision 1.13 since it was the most recent version at the time, I am also using python 3.8.

**Comment by liyuandagege** [comment]
thank you very much for your answer！

**Comment by jeonhuhuhu** [comment]
> Hi,
> 
> I suppose that I used PyTorch 1.12 with Torchvision 1.13 since it was the most recent version at the time, I am also using python 3.8.

The torchvision==1.13 version does not exist, isn't it the 0.13.1 version? And due to dependency issues, torch==1.12.1
I think so. No?
